/**
 * src/lib/rent-review-template.ts
 * HTML template for rent review letter PDF generation.
 */

export interface RentReviewLetterData {
  tenantName: string;
  propertyAddress: string;
  letterBody: string;
  generatedAt: string;
  landlordName?: string;
  landlordAddress?: string;
}

export function renderRentReviewLetterHTML(data: RentReviewLetterData): string {
  const landlordName = data.landlordName ?? "[Landlord Name]";
  const landlordAddress = data.landlordAddress ?? "[Landlord Address]";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lease Renewal Letter</title>
  <style>
    @page {
      size: A4;
      margin: 25mm;
    }
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #1a1a1a;
      background: #ffffff;
    }
    .letterhead {
      margin-bottom: 30px;
      padding-bottom: 15px;
      border-bottom: 1px solid #e0e0e0;
    }
    .letterhead-name {
      font-size: 14pt;
      font-weight: 600;
      color: #1a1a1a;
      margin-bottom: 4px;
    }
    .letterhead-address {
      font-size: 10pt;
      color: #666;
      line-height: 1.4;
    }
    .recipient {
      margin-bottom: 25px;
    }
    .recipient-name {
      font-weight: 600;
      margin-bottom: 2px;
    }
    .recipient-address {
      color: #333;
      white-space: pre-line;
    }
    .date {
      margin-bottom: 25px;
      color: #666;
      font-size: 10pt;
    }
    .letter-body {
      margin-bottom: 30px;
      white-space: pre-wrap;
      line-height: 1.8;
    }
    .letter-body p {
      margin-bottom: 12pt;
    }
    .signature-block {
      margin-top: 40px;
    }
    .signature-line {
      margin-top: 40px;
      padding-top: 2px;
      border-top: 1px solid #333;
      display: inline-block;
      min-width: 200px;
      font-size: 10pt;
      color: #666;
    }
    .footer {
      margin-top: 50px;
      padding-top: 15px;
      border-top: 1px solid #e0e0e0;
      font-size: 9pt;
      color: #999;
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="letterhead">
    <div class="letterhead-name">${escapeHtml(landlordName)}</div>
    <div class="letterhead-address">${escapeHtml(landlordAddress)}</div>
  </div>

  <div class="recipient">
    <div class="recipient-name">${escapeHtml(data.tenantName)}</div>
    <div class="recipient-address">${escapeHtml(data.propertyAddress)}</div>
  </div>

  <div class="date">${data.generatedAt}</div>

  <div class="letter-body">
    ${formatLetterBody(data.letterBody)}
  </div>

  <div class="signature-block">
    <div class="signature-line">Authorised Signatory</div>
  </div>

  <div class="footer">
    Generated by RealHQ — Commercial Property Intelligence Platform
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#039;",
  };
  return text.replace(/[&<>"']/g, (m) => map[m] ?? m);
}

function formatLetterBody(body: string): string {
  // Convert plain text to paragraphs
  const paragraphs = body.split(/\n\n+/);
  return paragraphs
    .map((p) => `<p>${escapeHtml(p.trim())}</p>`)
    .join("\n");
}
