/**
 * POST /api/user/rent-reviews/:reviewId/pdf
 * Generates a PDF for a renewal letter/correspondence.
 * Fixes PRO-695 Gap 2: Renewal letters can now be downloaded as PDF.
 *
 * Query param: ?correspondenceId=xxx (optional) - specific correspondence to render
 * If omitted, renders the most recent outbound correspondence for this review.
 *
 * Response: { pdfUrl: string | null }
 * - pdfUrl is a base64 data URI if successful
 * - null if PDF generation fails
 */

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { generateBrochurePDF } from "@/lib/brochure";
import type { RenewalCorrespondence } from "@/generated/prisma";

type PrismaWithCorrespondence = {
  renewalCorrespondence: {
    findFirst(q: object): Promise<RenewalCorrespondence | null>;
  };
};

function renderLetterHTML(data: {
  body: string;
  type: string;
  date: string;
  tenantName?: string;
  propertyAddress?: string;
}): string {
  // Simple letter-formatted HTML that matches dark theme design
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Instrument+Serif&display=swap');
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
  font-family: 'DM Sans', sans-serif;
  font-size: 11pt;
  line-height: 1.6;
  color: #111827;
  background: #fff;
  padding: 40mm 25mm;
}
h1, h2, h3 {
  font-family: 'Instrument Serif', Georgia, serif;
  font-weight: 400;
  margin-top: 1.5em;
  margin-bottom: 0.5em;
}
h1 { font-size: 18pt; margin-top: 0; }
h2 { font-size: 14pt; }
h3 { font-size: 12pt; }
p { margin-bottom: 0.8em; }
.header { margin-bottom: 30mm; }
.date { margin-bottom: 10mm; font-size: 10pt; color: #6B7280; }
.footer { margin-top: 40mm; font-size: 9pt; color: #9CA3AF; text-align: center; }
.signature-block { margin-top: 30mm; }
pre { white-space: pre-wrap; font-family: inherit; }
</style>
</head>
<body>
<div class="header">
  ${data.tenantName ? `<p><strong>${data.tenantName}</strong><br>` : ''}
  ${data.propertyAddress ? `${data.propertyAddress}</p>` : ''}
</div>
<div class="date">${data.date}</div>
<div class="body">
${convertToHTML(data.body)}
</div>
<div class="footer">
  <p>Generated by RealHQ on ${data.date}</p>
</div>
</body>
</html>`;
}

function convertToHTML(text: string): string {
  // Simple markdown-like conversion for letter body
  return text
    .split('\n\n')
    .map(para => {
      // Headings
      if (para.startsWith('# ')) return `<h1>${para.slice(2)}</h1>`;
      if (para.startsWith('## ')) return `<h2>${para.slice(3)}</h2>`;
      if (para.startsWith('### ')) return `<h3>${para.slice(4)}</h3>`;
      // Bold
      const withBold = para.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
      // Italic
      const withItalic = withBold.replace(/\*(.+?)\*/g, '<em>$1</em>');
      return `<p>${withItalic}</p>`;
    })
    .join('\n');
}

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ reviewId: string }> }
) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { reviewId } = await params;
  const url = new URL(req.url);
  const correspondenceId = url.searchParams.get("correspondenceId");

  const db = prisma as unknown as PrismaWithCorrespondence;

  // Load correspondence (either specific or most recent outbound)
  const correspondence = await db.renewalCorrespondence.findFirst({
    where: correspondenceId
      ? { id: correspondenceId, reviewId }
      : { reviewId, direction: "outbound" },
    orderBy: !correspondenceId ? [{ createdAt: "desc" }] : undefined,
  } as object);

  if (!correspondence) {
    return NextResponse.json({ error: "Correspondence not found" }, { status: 404 });
  }

  // Load review for context
  const review = await (prisma as { rentReviewEvent: { findFirst(q: object): Promise<{ tenantName: string; propertyAddress: string | null } | null> } }).rentReviewEvent.findFirst({
    where: { id: reviewId, userId: session.user.id },
    select: { tenantName: true, propertyAddress: true },
  } as object);

  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });

  const html = renderLetterHTML({
    body: correspondence.body,
    type: correspondence.type,
    date,
    tenantName: review?.tenantName,
    propertyAddress: review?.propertyAddress ?? undefined,
  });

  // Generate PDF using the same chromium pipeline as brochures
  let pdfUrl: string | null = null;
  try {
    // Use puppeteer directly since this is custom HTML, not BrochureData
    const chromium = await (async () => {
      try {
        return (await import("@sparticuz/chromium" as string) as { default: { args: string[]; executablePath: () => Promise<string>; headless: boolean } }).default;
      } catch { return null; }
    })();
    const puppeteer = await (async () => {
      try {
        return (await import("puppeteer-core" as string) as { default: { launch: (opts: object) => Promise<{ newPage: () => Promise<{ setContent: (h: string, opts: object) => Promise<void>; pdf: (opts: object) => Promise<Uint8Array> }>; close: () => Promise<void> }> } }).default;
      } catch { return null; }
    })();

    if (chromium && puppeteer) {
      const browser = await puppeteer.launch({
        args: chromium.args,
        executablePath: await chromium.executablePath(),
        headless: chromium.headless,
      });

      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: "networkidle0" });
      const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: { top: "10mm", bottom: "10mm", left: "0mm", right: "0mm" },
      });
      await browser.close();

      pdfUrl = `data:application/pdf;base64,${Buffer.from(pdfBuffer).toString("base64")}`;
    }
  } catch (err) {
    console.error("[rent-review/pdf] PDF generation failed:", err);
    // Non-fatal - return null
  }

  return NextResponse.json({ pdfUrl, htmlPreview: html });
}
